---

- include: setup-apt.yml
  sudo: Yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ 'tvheadend', 'apt' ]


- name: "config | ensure tvheadend service boots"
  sudo: yes
  service: enabled=yes  name=tvheadend state=started

